title: Jeopardy
description: "Sleek and sharp, might jeopardize your glance!"
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]

footer: "© 2025 <a href='https://gh.raghavkarn.com/jeopardy'>Raghav Karn</a> &mdash; MIT License"
author:
  name: Raghav Karn
  email: contact@raghavkarn.com
  url: https://jeopardy.raghavkarn.com

enable_dark_theme: true  